def generate_dorks(domain):
    dorks = [
        "site:{domain}",
        "site:{domain} intext:account",
        "site:{domain} intext:password",
        "site:{domain} inurl:login",
        "site:{domain} inurl:admin",
        "site:{domain} inurl:dashboard",
        "site:{domain} inurl:config",
        "site:{domain} inurl:backup",
        "site:{domain} ext:sql",
        "site:{domain} ext:log",
        "site:{domain} ext:txt",
        "site:{domain} ext:env",
        "site:{domain} ext:xml",
        "site:{domain} ext:json",
        "site:{domain} \"confidential\"",
        "site:{domain} \"internal use only\"",
        "site:{domain} \"do not share\"",
        "site:{domain} \"api_key\"",
        "site:{domain} \"secret\""
        "site:{domain} intitle:\"index of\" drupal",
        "site:{domain} intitle:\"index of\" admin",
        "site:{domain} inurl:login.cgi",
        "site:{domain} inurl:/joomla/administrator",
        "site:{domain} inurl:\"server-status\" intitle:\"Apache Status\" intext:\"Apache Server Status for\"",
        "site:{domain} inurl:/login/index.jsp",
        "site:{domain} intitle:\"Index of\" inurl:wp-json/oembed",
        "site:{domain} intitle:\"Index of\" phpmyadmin",
        "site:{domain} intitle:\"Index of\" wp-admin",
        "site:{domain} intitle:index.of.?.sql",
        "site:{domain} inurl:/filemanager/dialog.php",
        "site:amazonaws.com filetype:log",
        "site:{domain} inurl:cgi/login.pl",
        "site:zoom.us inurl:/j intext:\"scheduled for\"",
        "site:{domain} site:*/auth intitle:login",
        "site:{domain} inurl:admin/login.aspx",
        "site:{domain} \"Index of\" inurl:webalizer",
        "site:{domain} \"Index of\" inurl:phpmyadmin",
        "site:{domain} \"Index of\" inurl:htdocs inurl:xampp",
        "site:amazonaws.com intext:dhcp filetype:txt inurl:apollo",
        "site:{domain} inurl:/index.aspx/login",
        "site:amazonaws.com inurl:login.php",
        "site:{domain} intitle:\"IIS Windows Server\" -inurl:\"IIS Windows Server\"",
        "site:{domain} intitle:\"Apache2 Ubuntu Default Page: It works\"",
        "site:{domain} inurl:/filedown.php?file=",
        "site:{domain} inurl:Dashboard.jspa intext:\"Atlassian Jira Project Management Software\"",
        "site:{domain} inurl:app/kibana intext:\"Loading Kibana\"",
        "site:docs.google.com/spreadsheets edit",
        "site:{domain} intitle:\"index of\" unattend.xml",
        "site:{domain} inurl:/admin/index.php",
        "site:{domain} inurl:bc.googleusercontent.com intitle:\"index of\"",
        "site:{domain} inurl:office365 intitle:\"Sign In | Login | Portal\"",
        "site:{domain} intitle:OmniDB intext:\"user. pwd. Sign in.\"",
        "site:{domain} intitle:\"qBittorrent Web UI\" inurl:8080",
        "site:{domain} inurl:jboss filetype:log -github.com",
        "site:{domain} intitle:\"index of\" \".cpanel/caches/config/\"",
        "site:{domain} inurl:/scopia/entry/index.jsp",
        "site:{domain} intitle:\"index of\" \"/aws.s3/\"",
        "site:{domain} intitle:\"index of\" hosts.csv | firewalls.csv | linux.csv | windows.csv",
        "site:{domain} intitle:\"Test Page for the Nginx HTTP Server on Fedora\"",
        "site:{domain} inurl:_cpanel/forgotpwd",
        "site:{domain} intitle:\"index of /\" intext:/backup",
        "site:{domain} intitle:\"Swagger UI\"",
        "site:{domain} intext:\"class JConfig {\" inurl:configuration.php",
        "site:{domain} \"index of\" \"database.sql.zip\"",
        "site:{domain} ext:ini intext:env.ini",
        "site:{domain} ext:log inurl:\"password.log\"",
        "site:{domain} filetype:mdb inurl:users.mdb",
        "site:{domain} filetype:sql \"insert into\" (pass|passwd|password)",
        "site:{domain} intitle:\"index of\" etc/shadow",
        "site:{domain} intitle:\"index of\" htpasswd",
        "site:{domain} intitle:\"index of\" passwd",
        "site:{domain} intitle:\"index of\" mysql.conf",
        "site:{domain} inurl:php?id=",
        "site:{domain} inurl:index.php?id="
    ]      
    
    print("\n[+] Generated Google Dorks:\n")
    for dork in dorks:
        print(dork.replace("{domain}", domain))


if __name__ == "__main__":
    domain = input("Enter target domain (example: example.com): ").strip()
    generate_dorks(domain)
